title: Run production-grade databases easily on Kubernetes
baseurl: https://kubedb.com
languageCode: en-us
pluralizeListTitles: false
pygmentsStyle: "monokai"
pygmentsUseClasses: false
disqusShortname: appscode
staticdir: "build"
taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"
params:
  author: KubeDB Authors
  date_format: Mon, Jan 2, 2006
  description: Run production-grade databases easily on Kubernetes
  email: support@appscode.com
  logo: /images/logo.svg
  twitter_url: https://twitter.com/KubeDB
  slack_url: https://slack.appscode.com/
  issues_url: https://github.com/kubedb/project/issues/new
  youtube_url: https://www.youtube.com/c/appscode
  docker_url: https://hub.docker.com/u/kubedb
  contact_email: support@appscode.com
  sales_email: sales@appscode.com
  contact_phone: +1 (650) 241-8486
menu:
  main:
    - Name: "Database"
      identifier: database
      Weight: 1
      URL: https://kubedb.com/docs/latest/setup/install/
    - Name: "Documentation"
      Weight: 2
    - Name:
      Pre: "<i class='fa fa-github'></i>"
      Weight: 3
      Identifier: "GitHub"
      URL: "https://github.com/kubedb"
    - Name:
      Pre: "<i class='fa fa-twitter'></i>"
      Weight: 4
      Identifier: "twitter"
      URL: "https://twitter.com/KubeDB"
    - Name:
      Pre: "<i class='fa fa-users'></i>"
      Weight: 5
      Identifier: "groups"
      URL: "https://groups.google.com/forum/#!forum/kubedb"
    - Name:
      Pre: "<i class='fa fa-slack'></i>"
      Weight: 6
      Identifier: "slack"
      URL: "http://slack.kubernetes.io/"
    - Name:
      Pre: "<i class='fa fa-forumbee'></i>"
      Weight: 7
      Identifier: "forum"
      URL: "http://discourse.appscode.com"
    - Name: Elasticsearch
      identifier: elasticsearch
      parent: database
      weight: 10
    - Name: Memcached
      identifier: memcached
      parent: database
      weight: 20
    - Name: MongoDB
      identifier: mongodb
      parent: database
      weight: 30
    - Name: MySQL
      identifier: mysql
      parent: database
      weight: 40
    - Name: PostgreSQL
      identifier: postgres
      parent: database
      weight: 50
    - Name: Redis
      identifier: redis
      parent: database
      weight: 60
